### ISSUE TITLE
Flickering window

### ISSUE THREAD

**Issue by vdesabou** [weirdpattern/alfred-screen-capture-workflow#1]
Hi,

i've noticed that between 1st and 2nd script filter, the window is flickering, you can fix it by doing the following:-

![screen shot 2016-06-28 a 10 29 30](https://cloud.githubusercontent.com/assets/4061923/16408937/5a69af2e-3d1b-11e6-9c9a-a2686038436c.jpg)

Thanks for this workflow, it looks very good

**Comment by weirdpattern** [comment]
I added the window behavior as suggested, let me know if that improves things a bit.
To be honest, I still see the window flickering, but at least is better than before.
Thank you for reporting this and you are welcome to try my other workflows.
